### PR TITLE
Adding TCP optimizations for connections.

### PR DESCRIPTION
**Pull request by hekaldama**
Hey Aaron.

I added some TCP optimizations to http connections. Would you be able to test and release?

Thanks.

### CODE REVIEW

**Comment by aq1018** [comment]
@hekaldama

I have no means to test the TCP optimizations you desire. However, I can release a pre-version for you guys to test. Does that sound good to you?

I'm not again providing an interface for TCP socket options. But I think forcing `NODELAY` option by default is too opinionated. We should follow the principle of the least surprise and let users make the choice.

**Comment by hekaldama** [comment]
Okay. I was mostly copying what @drbrain did in net-http-persistent because he is much smarter than I. I am fine either way though.

**Comment by drbrain** [comment]
I have TCP_NODELAY set because of the write-write-read problem with Nagle's algorithm and HTTP requests with bodies (POST and PUT):

https://bugs.ruby-lang.org/issues/8681

**Comment by aq1018** [comment]
Thanks Eric,

Now that makes a lot more sense.

**Comment by aq1018** [comment]
Released: http://rubygems.org/gems/gateway-http/versions/0.3.0

Thanks guys!

**Pull request merged**
